### ISSUE TITLE
Twitter chats to be promoted and into Webmaker events

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#152]
A huge win from this training is all the emerging participant-hosted Twitter chats. 

A few ideas to keep those rolling and have them count towards our contributor numbers:
- Write a quick Discourse post about the benefits of running a Twitter chat. Include the recommended format, quick how-to, and what you'd get out of it (inc. meeting people, learning more about a topic)
- Prompt for / figure out how we can get participants to list Twitter chats on events.webmaker.org. These will then count automatically as contribution and give more visibility. 
-  Send Twitter chat calendar & details to Engagement team to tweet / spread the word. 
- Add a link or section to hosting a Twitter chat in the "Host a training" page: http://training.webmakerprototypes.org/en/host-a-training/

**Comment by LauraHilliger** [comment]
- Ok edited the topic description: http://discourse.webmakerprototypes.org/t/engage-people-and-extend-your-network-with-twitter-chats/128
- sent live session category and calendar to Engagement
- for the host a training page, I started drafting text here: https://teach.etherpad.mozilla.org/training-live-sessions @thornet line 92 starts getting into online stuff people could do. Would love some help/feedback there
- finally, I think we should have a chat about contribution logging. May be too much of a pull to ask people to post in multiple places. I can prompt people to schedule it using events instead of a new discourse topic, but I can't keep track of it in that way AFAIK. Maybe this is the beginning of a convo around IRL & Online learning experiences...

**Comment by thornet** [comment]
Awesome! 
- Added some edits to the "host a training" etherpad. 
- Re: contrib logging: if we think it's too high-bar for people to post on wm.org, then we should at least be capturing their chats & emails to log them in the ad-hoc logger. It can be done after training, as long as we have a way of readily finding that info.

**Comment by LauraHilliger** [comment]
+1 to logging them! 
Twitter chat hosts anyway, but do we also consider discussing in the Discourse contribution? Because we can export active users and import into the adhoccer.
