### ISSUE TITLE
Make training badges visible on site

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#158]
Hey, 

We shouldn't just bury training badges. Why not add a big section on the landing page (you can earn these badges!) and in each module (did all this? get a badge!)

Reference: http://discourse.webmakerprototypes.org/t/ready-webmaker-training-badges/387

These are really important to see who's active. Let's shout to the rooftops!

**Comment by dajbelshaw** [comment]
This is a great idea. Perhaps instead of on the landing page, we could infuse across the site?

So I'd go for creating a separate 'badge' page and linking to it from multiple places. In some places that can be a graphic link and some places a text link.
1. [Home](http://training.webmakerprototypes.org/en/) page
   ![Home](http://i.imgur.com/9o2v8d1.png)
2. [Start here](http://training.webmakerprototypes.org/en/start-here/) page
   ![Start here](http://i.imgur.com/DQjRYV4.png)
3. Add badges to module pages - e.g. [Exploring](http://training.webmakerprototypes.org/en/exploring/concepts/)
   ![Exploring](http://i.imgur.com/WSyy8jK.png)

---

Other places to add include Discourse (in each thread) and...?

**Comment by dajbelshaw** [comment]
Actually, after leaving that comment, I think a better place for a new 'Badges' page to reside would be next to 'Calendar' and 'Discussion' (underneath P2PU logo). What do you think?

**Comment by LauraHilliger** [comment]
commit 3082147
